insert into restaurant (name, email, info, phoneNumber, website, city, street, houseNumber, zipCode, localizationUrl) VALUES ("Jadka", "restauracja@jadka.pl", "Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras justo ligula, tincidunt sed egestas sed, accumsan a dui. Fusce diam nulla, ultrices sit amet lorem nec, tempus dignissim orci. Phasellus at venenatis nisl", "+48 123456789", "http://www.jadka.pl", "Warszawa", "Plac Konstytucji", "4", "00-123", "https://www.openstreetmap.org/export/embed.html?bbox=21.01391673088074%2C52.22051905976723%2C21.018216311931614%2C52.22198804350747&amp;layer=mapnik&amp;marker=52.22125355771131%2C21.016066521406174");
insert into restaurant (name, email, info, phoneNumber, website, city, street, houseNumber, zipCode, localizationUrl) VALUES ("Mniam Mniam", "kontakt@mniammniam.com.pl", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam malesuada convallis massa non tristique. Proin sed aliquam neque. In vestibulum facilisis eros, quis volutpat dolor ultricies sit amet. Maecenas varius dui sagittis venenatis mattis. Donec ac aliquam metus. Vestibulum felis dolor, ornare eget lacinia non, vulputate ut elit", "+48 123456789", "http://www.mniam.com.pl/", "Warszawa", "Marszalkowska", "23", "00-111", "https://www.openstreetmap.org/export/embed.html?bbox=21.013568043708805%2C52.22414377953833%2C21.016928851604465%2C52.22561264337765&amp;layer=mapnik&amp;marker=52.22487821753176%2C21.01524844765663");
insert into restaurant (name, email, info, phoneNumber, website, city, street, houseNumber, zipCode, localizationUrl) VALUES ("Amciu", "kontakt@amciu.pl", "Nulla facilisi. Maecenas leo ipsum, placerat commodo neque sit amet, condimentum imperdiet eros. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce tempor lacus sed eros ullamcorper, quis venenatis urna posuere. Sed posuere magna vitae purus imperdiet ornare. ", "+48 123456789", "http://amciu.pl", "Warszawa", "Marszalkowska", "115", "00-131", "https://www.openstreetmap.org/export/embed.html?bbox=21.00169658660889%2C52.24066980244217%2C21.00505739450455%2C52.24213811954793&amp;layer=mapnik&amp;marker=52.24140396706791%2C21.003376990556717");
insert into restaurant (name, email, info, phoneNumber, website, city, street, houseNumber, zipCode, localizationUrl) VALUES ("Pychota", "example@mail.pl", "Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla sit amet ante quis ante semper fermentum. Aliquam malesuada urna eget mollis faucibus. Duis vestibulum, sapien in fringilla volutpat, orci massa pharetra dui, pharetra maximus libero tortor eget ipsum. Nulla consequat in eros quis fringilla", "+48 123456789", "http://www.example.pl", "Warszawa", "Kokoszki", "4", "12-345", "https://www.openstreetmap.org/export/embed.html?bbox=20.987105369567875%2C52.228509153054844%2C20.99398791790009%2C52.23086170930667&amp;layer=mapnik&amp;marker=52.229685446763725%2C20.99054664373398");
insert into restaurant (name, email, info, phoneNumber, website, city, street, houseNumber, zipCode, localizationUrl) VALUES ("Ulala", "biuro@ulala.pl", "Morbi nec posuere tortor. Proin at est nec nisi pellentesque luctus. Morbi nisi nisl, dictum vitae felis sit amet, rhoncus placerat risus. Aliquam enim orci, sollicitudin ac scelerisque vel, tincidunt eu arcu. Nunc hendrerit aliquam turpis, at hendrerit arcu cursus ac. Nam sit amet lacus vel lorem gravida semper. ", "+48 123456789", "http://ulala.pl", "Warszawa", "Krolewska", "4", "00-543", "https://www.openstreetmap.org/export/embed.html?bbox=21.01435393095017%2C52.239768093698615%2C21.01771473884583%2C52.241236440638964&amp;layer=mapnik&amp;marker=52.24050230002817%2C21.01603350000005");
insert into restaurant (name, email, info, phoneNumber, website, city, street, houseNumber, zipCode, localizationUrl) VALUES ("Niebo w gębie", "niebo@wgebie.com", "Curabitur gravida semper libero, eget egestas massa tempus nec. In facilisis maximus sapien, eu tempus est consectetur sed. Mauris imperdiet erat nec mauris cursus finibus. In hac habitasse platea dictumst. ", "+48 123456789", "http://niebowgebie.com", "Warszawa", "Zwirki i Wigury", "454", "02-023", "https://www.openstreetmap.org/export/embed.html?bbox=20.987456738948822%2C52.210239743672474%2C20.990817546844486%2C52.21170906740699&amp;layer=mapnik&amp;marker=52.21097385013508%2C20.98913755000001");

insert into promotion (category, name, description, price, dayOfWeek, restaurant_id) values ("Obiady domowe", "Sznycel jak w Wiedniu z ćwiartka cytryny i salatka ziemniaczana lub frytkami", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce vehicula vulputate nisl in facilisis. Morbi placerat, mi id convallis accumsan, mi nisl blandit leo, non interdum velit elit rhoncus dolor. Integer efficitur ipsum et ornare faucibus. Aenean nec laoreet odio. Nunc a pretium lectus, in posuere nisl.", 17.00, 1, 1);
insert into promotion (category, name, description, price, dayOfWeek, restaurant_id) values ("Owoce morza", "Mule w garnku na cztery sposoby do wyboru", "Proin convallis at velit eu lacinia. Vivamus velit eros, venenatis sit amet neque quis, interdum bibendum est. Vivamus varius elit vitae nunc posuere, at efficitur dui interdum. Morbi convallis turpis ut ante elementum ullamcorper id nec urna. Phasellus at diam ornare, varius tellus sodales, pellentesque purus. ", 44.00, 4, 1);
insert into promotion (category, name, description, price, dayOfWeek, restaurant_id) values ("Obiady domowe", "Sur Sznycel 100% peklowanego miesa z cwiartka cytryny i l ziemniaczana lub frytkami", "Integer vulputate odio id metus laoreet, eu hendrerit ex faucibus. Nunc a libero tristique, rutrum urna nec, ullamcorper enim. Pellentesque porttitor vehicula nulla nec ultricies. Aenean tortor nisi, commodo ut tincidunt eu, bibendum quis velit. Proin egestas lectus ut sem dictum, id iaculis libero lobortis.", 19.00, 3, 1);
insert into promotion (category, name, description, price, dayOfWeek, restaurant_id) values ("Obiady domowe", "Golonka z pieca", "Donec id ligula est. Sed porttitor, est sed maximus tempus, enim purus gravida eros, sit amet consequat justo diam nec elit. Quisque luctus risus lorem, eu lobortis sem mollis eget. In est tellus, auctor quis diam vitae, fermentum venenatis est. Praesent mollis vel nisi vel euismod. Pellentesque a volutpat ex. Vivamus eget tempus nunc.", 5.00, 6, 1);
insert into promotion (category, name, description, price, dayOfWeek, restaurant_id) values ("Burger", "Burgery z naszego menu (poza burgerem 300)", "Donec pellentesque vitae nunc quis dapibus. Suspendisse pretium maximus ante vel lacinia. Pellentesque nisl nibh, sagittis quis mattis id, bibendum id urna. Quisque a metus maximus, laoreet arcu vitae, tempor velit. ", 21.90, 3, 2);
insert into promotion (category, name, description, price, dayOfWeek, restaurant_id) values ("Obiady domowe", "Stek z rostbefu", "In urna est, lobortis ultricies tortor non, commodo placerat magna. Duis in mauris ut lectus sagittis aliquet vel a ligula. Nulla rutrum turpis lectus, vel iaculis quam auctor et. Pellentesque id venenatis arcu. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut tempus dignissim elit, ut lobortis lacus pulvinar ut.", 33.90, 5, 2);
insert into promotion (category, name, description, price, dayOfWeek, restaurant_id) values ("Owoce morza", "Mule", "Maecenas quis luctus ex. Vivamus hendrerit mi sit amet lacus ornare vulputate non id nisl. Proin accumsan nulla dui, commodo tincidunt tellus efficitur elementum. Praesent sem velit, lacinia vel suscipit in, efficitur nec ipsum. Nullam congue purus non metus ultricies imperdiet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce ac semper lectus. ", 39.90, 4, 3);
insert into promotion (category, name, description, price, dayOfWeek, restaurant_id) values ("Obiady domowe", "Dwie porcje SKRZYDELEK BBQ", "Cras et diam accumsan, cursus quam in, luctus sapien. Aenean accumsan eros nec massa ullamcorper dapibus. Donec in felis ac nunc pretium laoreet eget eget augue. Vestibulum aliquam mi urna, ut condimentum ante interdum et. Duis dui justo, sollicitudin quis gravida suscipit, aliquet non leo. Mauris ac lobortis quam. Cras sollicitudin efficitur tortor sit amet rutrum.", 25.00, 4, 5);
insert into promotion (category, name, description, price, dayOfWeek, restaurant_id) values ("Obiady domowe", "Schabowy", "Ut eu velit sit amet lectus blandit tincidunt et vitae arcu. Mauris quis mi erat. Proin et velit egestas, efficitur nisl sit amet, lobortis lorem. Aenean iaculis ante id ex dapibus interdum. Aenean elementum malesuada lacus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.", 15.00, 1, 5);
insert into promotion (category, name, description, price, dayOfWeek, restaurant_id) values ("Obiady domowe", "Teriyaki Pork Steak", "Quisque felis lectus, tincidunt eu ante vulputate, sodales rutrum nunc. Sed ex ipsum, elementum non fermentum id, volutpat in felis. Vivamus id lectus tellus. ", 20.00, 1, 6);
insert into promotion (category, name, description, price, dayOfWeek, restaurant_id) values ("Naleśniki", "Czekoladowe naleśniory", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis malesuada metus a suscipit rhoncus. Maecenas lobortis aliquet augue, et lobortis dui scelerisque sit amet. Curabitur facilisis odio at nulla posuere, in ullamcorper massa pharetra. Phasellus mattis sapien a diam molestie ultrices. Nunc vitae feugiat ligula, viverra porta magna.", 13.00, 3, 3);
insert into promotion (category, name, description, price, dayOfWeek, restaurant_id) values ("Pierogi", "Pierogi ze szpinakiem", "Pellentesque urna sem, venenatis ac iaculis nec, sodales eget enim. Aenean feugiat laoreet leo. Donec cursus cursus nulla vitae tempor. Aenean fringilla pretium sapien, eget scelerisque mauris. ", 15.50, 4, 2);
insert into promotion (category, name, description, price, dayOfWeek, restaurant_id) values ("Kebab", "Baranina w bułce z ostrym sosem", "Aliquam eu lorem purus. Cras ullamcorper felis non iaculis lacinia. Vivamus rhoncus, urna accumsan mattis imperdiet, sem dolor pharetra erat, eget elementum nibh odio blandit mauris. Quisque tellus tortor, laoreet eget dui nec, porttitor mollis eros. Aliquam lobortis dui eu ligula placerat, eu faucibus risus maximus.", 11.45, 2, 1);
insert into promotion (category, name, description, price, dayOfWeek, restaurant_id) values ("Sushi", "Ryba w ryżu owinieta glonem", "Mauris congue scelerisque mauris, quis auctor velit mollis sit amet. Donec nunc neque, pellentesque id ornare non, porta eu eros. Etiam sed ornare lectus. ", 32.49, 0, 6);
insert into promotion (category, name, description, price, dayOfWeek, restaurant_id) values ("Alkohole", "Butelka Bordeaux", "Duis hendrerit posuere neque vel porta. Aliquam vitae felis eu nunc cursus euismod. Pellentesque dolor est, maximus vitae nisl vitae, blandit accumsan dolor. Nullam ut volutpat sem, a consequat mauris. Maecenas sagittis eu dolor vitae rhoncus. Sed vel lorem lacinia, convallis orci laoreet, dictum ante. Aliquam erat volutpat.", 45.99, 5, 4);
insert into promotion (category, name, description, price, dayOfWeek, restaurant_id) values ("Ramen", "Miso mura mina jama", "Vestibulum a quam non ipsum finibus semper nec euismod libero. In rutrum purus nec neque fermentum, ac lobortis magna sagittis. Suspendisse potenti. Fusce sed euismod nibh. ", 28.00, 6, 5);
insert into promotion (category, name, description, price, dayOfWeek, restaurant_id) values ("Makarony", "Spaghetti Bolognese", "Pellentesque placerat vestibulum urna, quis imperdiet sapien egestas ac. Integer tortor lorem, viverra vel lacus vel, aliquam malesuada ligula. Nulla enim eros, aliquam et porttitor in, fringilla nec tellus. Nam eget rutrum ipsum, id consequat nunc", 18.00, 1, 2);
insert into promotion (category, name, description, price, dayOfWeek, restaurant_id) values ("Pizza", "Pizza Margheritta", "Curabitur augue nibh, congue vel lectus eget, efficitur condimentum elit. Fusce at dui sed erat ultrices vestibulum. Suspendisse ultrices dictum neque ut elementum. Aliquam iaculis libero sed metus porta cursus. ", 11.00, 2, 2);

insert into userDetails (address, dateOfBirth, email) values ("Warszawa","01-02-2000", "test@test.pl");
insert into userDetails (address, dateOfBirth, email) values ("Warszawa","01-02-2000", "test@test.pl");
insert into userDetails (address, dateOfBirth, email) values ("Warszawa","01-02-2000", "test@test.pl");

insert into users (password, username, userDetails_id) values ("$2a$10$xF1rNrQSliDv64JuR9xsueR8Lv503g03vm7uDjQBQFxcNbZCBDqIO", "kubakuba", 1);
insert into users (password, username, restaurant_id, userDetails_id) values ("$2a$10$xF1rNrQSliDv64JuR9xsueR8Lv503g03vm7uDjQBQFxcNbZCBDqIO", "restaurant", 1, 2);
insert into users (password, username, userDetails_id) values ("$2a$10$xF1rNrQSliDv64JuR9xsueR8Lv503g03vm7uDjQBQFxcNbZCBDqIO", "admin", 3);

insert into role (name) value ("ROLE_ADMIN");
insert into role (name) value ("ROLE_USER");
insert into role (name) value ("ROLE_RESTAURATEUR");

insert into users_role (users_id, roles_id) values (1,2);
insert into users_role (users_id, roles_id) values (2,3);
insert into users_role (users_id, roles_id) values (3,1);

